### PR TITLE
Improve docstring for SL

### PR DESCRIPTION
**Pull request by psteinb**
Looking forward to feedback on this. Haven't checked the sbibm paper yet, if it would lend a better explanation.

### CODE REVIEW

**Comment by jan-matthis** [comment]
Thanks for this!

Some extra context: We used SynthLikNet as a quick implementation of the classical synthetic likelihood algorithm published by Wood (2010). It is reported as SL on the website and in the paper's appendix.

**Comment by psteinb** [comment]
Cool, I'll have a look and add the reference in due course.

**Comment by psteinb** [comment]
Ready to go from my side @jan-matthis

**Comment by psteinb** [comment]
The test for `sl.py` I added fails at this point. But I gather that have a failing test is better than having no test.

**Comment by jan-matthis** [comment]
Cheers!

**Pull request merged**
